/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hermes.client.vue;

import hermes.client.controleur.Chatter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Menini Thomas (d120041) <t.menini@student.helmo.be>
 */
public final class ChatGUI extends javax.swing.JFrame implements Chat {

    private final Chatter chat;

    /**
     * Creates new form Chat
     *
     * @param chatter
     * @param users
     */
    public ChatGUI(Chatter chatter, DefaultListModel users) {
        initComponents();
        utilisateurs.setModel(users);
        chat = chatter;
        setChatListener();

        //centre la frame
        setLocationRelativeTo(getRootPane());

        //Scroll automatiquement en bas du textarea
        DefaultCaret caret = (DefaultCaret) conversation.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }

    public String getUtilisateur() {
        return utilisateur.getText();
    }

    public void setUtilisateur(String utilisateur) {
        this.utilisateur.setText(utilisateur);
    }

    private void setChatListener() {
        message.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                if (ke.getKeyChar() == '\n') {
                    envoyer.doClick();
                }
            }
        });
        envoyer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                chat.entrer(utilisateur.getText(), message.getText());
                message.setText("");
            }
        });
    }

    @Override
    public void afficher(String text) {
        conversation.append(text);
        conversation.append("\n");
    }

    @Override
    public void avertir(String titre, String message) {
        JOptionPane.showMessageDialog(this, message, titre,
                JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dialogue = new javax.swing.JPanel();
        message = new javax.swing.JTextField();
        envoyer = new javax.swing.JButton();
        utilisateur = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        conversation = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        utilisateurs = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IRC Helmo");
        setName("client"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                femer(evt);
            }
        });

        dialogue.setPreferredSize(new java.awt.Dimension(477, 40));
        dialogue.setLayout(new java.awt.GridBagLayout());

        message.setPreferredSize(new java.awt.Dimension(400, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        dialogue.add(message, gridBagConstraints);

        envoyer.setText("Envoyer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.1;
        dialogue.add(envoyer, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        dialogue.add(utilisateur, gridBagConstraints);

        getContentPane().add(dialogue, java.awt.BorderLayout.PAGE_END);

        conversation.setEditable(false);
        conversation.setColumns(20);
        conversation.setRows(5);
        scrollPane.setViewportView(conversation);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 27));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 130));

        jScrollPane1.setViewportView(utilisateurs);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.EAST);

        jMenu1.setText("File");

        jMenuItem4.setText("Quitter");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Overlay");

        jMenuItem1.setText("Overlay 1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Overlay 3");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Overlay 5");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);
        jMenu2.add(jSeparator1);

        jMenuItem5.setText("Desactiver");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femer(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_femer
        chat.fermer();
    }//GEN-LAST:event_femer

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        chat.afficherOverlay(1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        chat.afficherOverlay(3);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        chat.afficherOverlay(5);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        chat.desactiverOverlay();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        chat.fermer();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea conversation;
    private javax.swing.JPanel dialogue;
    private javax.swing.JButton envoyer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField message;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField utilisateur;
    private javax.swing.JList utilisateurs;
    // End of variables declaration//GEN-END:variables

}
