/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.vue;

import client.controleur.chatter.Chatter;
import client.vue.stream.JTextAreaOutputStream;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.OutputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author Menini Thomas (d120041) <t.menini@student.helmo.be>
 */
public final class Chat extends javax.swing.JFrame {

    private final Chatter chat;
    private final OutputStream ouput;

    /**
     * Creates new form Chat
     *
     * @param chatter
     */
    public Chat(Chatter chatter) {
        initComponents();
        chat = chatter;
        ouput = new JTextAreaOutputStream(conversation);
        setChatListener();
    }

    public OutputStream getOutputStream() {
        return ouput;
    }

    public void setChatListener() {
        message.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                if(ke.getKeyChar() == '\n') {
                    envoyer.doClick();
                }
            }
        });
        envoyer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                chat.send(message.getText());
                message.setText("");
            }
        });
    }

    public void entrer(String text) {
        conversation.append(text);
        conversation.append("\n");
    }

    public void avertir(String titre, String message) {
        JOptionPane.showMessageDialog(this, message, titre,
                JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dialogue = new javax.swing.JPanel();
        message = new javax.swing.JTextField();
        envoyer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        conversation = new javax.swing.JTextArea();

        setTitle("IRC Helmo");
        setName("client"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                femer(evt);
            }
        });

        dialogue.setPreferredSize(new java.awt.Dimension(477, 40));
        dialogue.setLayout(new java.awt.GridBagLayout());

        message.setPreferredSize(new java.awt.Dimension(400, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        dialogue.add(message, gridBagConstraints);

        envoyer.setText("Envoyer");
        dialogue.add(envoyer, new java.awt.GridBagConstraints());

        getContentPane().add(dialogue, java.awt.BorderLayout.PAGE_END);

        conversation.setEditable(false);
        conversation.setColumns(20);
        conversation.setRows(5);
        jScrollPane2.setViewportView(conversation);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femer(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_femer
        chat.close();
    }//GEN-LAST:event_femer

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea conversation;
    private javax.swing.JPanel dialogue;
    private javax.swing.JButton envoyer;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField message;
    // End of variables declaration//GEN-END:variables
}
